site_name: Platforms, Microservices, DevOps and APIs
site_author: Ana Beatriz da Cunha, Gustavo Santana
site_url: https://insper.github.io/microservices
repo_url: https://github.com/microservices-26-1/microservices
repo_name: microservices-26-1/microservices

theme:
  name: material
  palette:
    # primary: grey
    # Light mode
    - scheme: default
      primary: grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.path
    - navigation.tracking
  icon:
    # logo: assets/images/devops
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  # logo: assets/images/logo.png

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - markdown_grid_tables:
  - markdown_include.include:
      base_path: docs
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables


plugins:
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors
  - git-committers:
      repository: microservices-26-1/microservices
      branch: main
      token: !ENV MKDOCS_GIT_COMMITTERS_APIKEY
  - search
  - minify:
      minify_html: true
  - badges
  - markdown-exec
  - mkdocs-pdf
  - render_swagger:
      allow_arbitrary_locations : true
  - termynal:
      prompt_literal_start:
        - "$"
        - ">"

# extra_javascript:
#   - assets/javascripts/mathjax.js
#   - https://polyfill.io/v3/polyfill.min.js?features=es6
#   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# extra_css:
#   - assets/stylesheets/extra.css

nav:
  - Home: index.md

  # - Classes:
  #   - 1. Distributed Systems: classes/distributed_systems/index.md
  #   - 2. Containerization: classes/containerization/index.md
  #   - 3. Microservices: classes/microservices/index.md
    # - 4. Architectures: classes/architectures/index.md
    # - 5. API: classes/api/index.md
    # - 6. DevOps: classes/devops/index.md
    # - 7. Cloud: classes/cloud/index.md
    # - 8. Orchestration: classes/orchestration/index.md
    # - 9. Reliability: classes/reliability/index.md
    # - 10. Cloud Service Models: classes/cloud_service_models/index.md