site_name: Platforms, Microservices, DevOps and APIs
site_author: Ana Beatriz da Cunha, Gustavo Santana
site_url: https://insper.github.io/microservices
repo_url: https://github.com/microservices-26-1/microservices
repo_name: microservices-26-1/microservices

theme:
  name: material

  palette:

    # Dark mode
    - scheme: slate
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Light mode

    # Light mode
    - scheme: default
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Dark mode

  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - search.highlight
    - navigation.top

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Arquitetura: arquitetura.md
  - Serviços: servicos.md
  - Execução: execucao.md
  - Diagramas: diagramas.md
  - API: api.md