
name: project-api

services:

  db:
    image: postgres:17
    hostname: db
    ports:
      - 5432:5432
    volumes:
      - ${VOLUME_DB}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER:-store}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-devpass}
      POSTGRES_DB: ${DB_NAME:-store}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-store}"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    hostname: gateway
    environment:
      CORS_ALLOWED_CREDENTIALS: ${CORS_ALLOWED_CREDENTIALS:-true}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-*}
    ports:
      - 8080:8080

  
  account:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    hostname: account
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_DB: ${DB_NAME:-store}
      DATABASE_USERNAME: ${DB_USER:-store}
      DATABASE_PASSWORD: ${DB_PASSWORD:-devpass}
    deploy:
      replicas: 1
    depends_on:
      db:
        condition: service_healthy

  auth:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    hostname: auth
    deploy:
      replicas: 1
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-jYCiN0YPiaBP53bGJi/kjfw79HW7xnBu9UPoD/QFFAE=}
      JWT_HTTP_ONLY: ${JWT_HTTP_ONLY:-true}
    depends_on:
      - account

  product:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    hostname: product
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_DB: ${DB_NAME:-store}
      DATABASE_USERNAME: ${DB_USER:-store}
      DATABASE_PASSWORD: ${DB_PASSWORD:-devpass}
    deploy:
      replicas: 1
    depends_on:
      db:
        condition: service_healthy

  order:
      build:
        context: ./order-service
        dockerfile: Dockerfile
      hostname: order
      environment:
        DATABASE_HOST: db
        DATABASE_PORT: 5432
        DATABASE_DB: ${DB_NAME:-store}
        DATABASE_USERNAME: ${DB_USER:-store}
        DATABASE_PASSWORD: ${DB_PASSWORD:-devpass}
      deploy:
        replicas: 1
      depends_on:
        db:
          condition: service_healthy

  exchange:
    build:
      context: ./exchange
      dockerfile: Dockerfile
    hostname: exchange
    deploy:
      replicas: 1
    environment:
      EXCHANGE_API_KEY: ${EXCHANGE_API_KEY}

  prometheus:
    image: prom/prometheus:latest
    hostname: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./volume/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-enterprise
    hostname: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./volume/grafana:/var/lib/grafana
      - ./volume/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources      
    restart: always
    depends_on:
      - prometheus